### ISSUE TITLE
Email Addon lässt sich auf CCU3 nicht installieren

### ISSUE THREAD

**Issue by DaTommy83** [homematic-community/hm_email#12]
Bei der Installation des EMail Addons in der aktuellen Version hängt sich die CCU3 auf und ist nicht mehr ansprechbar. Nach Neustart funktioniert sie wieder, das Addon wurde jedoch nicht installiert.

**Comment by corbeau-jr** [comment]
Das betrifft nicht nur das EMail AddOn, sondern auch andere AddOns. Bei Wiederholung nach Neustart funktioniert es bei mir meist nach dem zweiten / dritten Mal. Ärgerlich...
