### ISSUE TITLE
E-Mail-Versand mit TLS 1.2 nicht möglich

### ISSUE THREAD

**Issue by Apfelgelee** [homematic-community/hm_email#15]
Hallo zusammen,

 nachdem mein ISP Domainfactory heute Nacht auf seinen SMTP-Servern TLS 1.0/1.1 deaktiviert und damit zwangsweise auf TLS 1.2 umgestellt hat, ist ein Mail-Versand von meiner CCU2 mit dem E-Mail-Addon nicht mehr möglich. Ich erhalte in den Logs die folgenden Fehlermeldungen:

- Email-Log: May 20 10:51:38 host=smtprelaypool.ispgateway.de tls=on auth=on user=xxx from=xxx recipients=xxx errormsg='cannot read from TLS connection: a protocol violating EOF occured' exitcode=EX_IOERR
- CCU-Syslog: May 20 10:51:38 homematic-ccu2 user.err email: msmtp: cannot read from TLS connection: a protocol violating EOF occured msmtp: could not send mail (account default from /etc/config/addons/email/msmtp.conf)

Lässt sich diese Umstellung auf TLS 1.2 im Mail-Plugin realisieren? Vielen Dank vorab. Im Fall von Rückfragen stehe ich gerne zur Verfügung.

Viele Grüße

Apfelgelee

**Comment by jens-maus** [comment]
Existiert dieses Problem mit aktuellster CCU2 Firmware noch, denn das Problem geht auf veraltete OpenSSL Bibliotheken bei älteren CCU2 Firmwares zurück.

**Comment by Apfelgelee** [comment]
Hallo Jens,

 vielen Dank für deine Antwort. Es wäre toll, wenn ich die E-Mail von der CCU wieder über "meinen" Mailserver versenden kann.

 Da ich diese Woche noch eine Menge zu tun habe, komme ich leider erst am Wochenende dazu, die CCU zu aktualisieren und den Mailversand mit TLS 1.2 zu testen. Ich werde spätestens Anfang kommender Woche an dieser Stelle die Ergebnisse teilen.


Viele Grüße 

Apfelgeele

**Comment by Apfelgelee** [comment]
Hallo Jens,

 ich bin doch schon etwas eher als geplant zum Testen gekommen. Ich habe ein Update der CCU2 auf Firmware Version **2.53.34** durchgeführt. Ebenso habe ich die Gelegenheit genutzt und das Mail-Plugin auf die neue Version **1.7.0** hoch gezogen.

 Ergebnis: Mit der genannten Firmware-Version wird TLS 1.2 uneingeschränkt unterstützt und ich kann wieder meinen eigenen Mail-Server zum Versand nutzen ==> Alles bestens.


Vielen Dank und viele Grüße

Apfelgelee
