### ISSUE TITLE
Keine Anzeige von Einsellungen seit Update auf 1.7.0

### ISSUE THREAD

**Issue by libertyx82** [homematic-community/hm_email#16]
![image](https://user-images.githubusercontent.com/22996350/98439944-c50d6d80-20f5-11eb-900d-1df1b16a1576.png)
![image](https://user-images.githubusercontent.com/22996350/98439933-a4ddae80-20f5-11eb-9c3c-332d5b55cd22.png)
![image](https://user-images.githubusercontent.com/22996350/98439937-b0c97080-20f5-11eb-9765-8b8671014e74.png)

Chrome gibt folgenden Fehler auf der Console aus
```
    Uncaught SyntaxError: Unexpected token ' in JSON at position 4494        ?sid=@VCQcYOu2ky@:119 
    at JSON.parse (<anonymous>)
    at startup (email.js:563)
    at onload (?sid=@VCQcYOu2ky@:10)
```
Das versenden von Mails funktioniert allerdings.

**Comment by ptweety** [comment]
Scheint damit also etwas mit 49895b081660404c2add8ec85c8483610bc0f91a zu tun zu haben. @jens-maus die SessionID ist nur innerhalb des `if` definiert, wird dann aber von `JSON.parse`verwendet.

**Comment by ptweety** [comment]
@libertyx82 kannst du ggfs. ein **anonymisiertes Backup** deiner Dateien zur Verfügung stellen. Dann lässt sich der Fehler leichter nachvollziehen.

```
MAIL_DIR=/usr/local/etc/config/addons/email/mails
MSMTP_CONF=/usr/local/etc/config/addons/email/msmtp.conf
ACCOUNT_CONF=/usr/local/etc/config/addons/email/account.conf
USER_SCRIPT=/usr/local/etc/config/addons/email/userscript.tcl
```

**Comment by jens-maus** [comment]
Also ich denke auch das es an dem `JSON.parse()` liegt. Daher auch die Bitte von mir an @libertyx82 das er bitte ein versionen seiner oben gezeigten configs hier zeigt. Momentan gehe ich davon aus das hier irgendwie ein invalides JSON generiert wird und das dazu führt das die JSON.parse() funktion dann eben die gezeigte Fehlermeldung/Exception schmeisst.

**Comment by libertyx82** [comment]
[email-backup.zip](https://github.com/homematic-community/hm_email/files/5524818/email-backup.zip)

**Comment by WickedScav** [comment]
[email-backup.zip](https://github.com/homematic-community/hm_email/files/5525178/email-backup.zip)

Hab das identische Problem nach dem Upgrade von 1.6.8c auf 1.7.0. Benutze nur 10.mail bis 14.mail, die anderen Dateien müssten identisch mit dem Originalen sein.

Könnte das Problem ein Apostroph in einer Texteingabe sein? Also ohne Unicode, sondern nur [']? So wie bei mir im Fall von "10.mail"?
